using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using System.Security.Cryptography;

Console.WriteLine("=== Admin Account Bootstrap Generator ===\n");

var adminEmail = ReadRequired("Admin email");
var adminPassword = ReadRequired("Admin password");
var adminName = ReadWithDefault("Admin full name", "System Administrator");
var officeLocation = ReadWithDefault("Office location", "Main Office");
var status = ReadWithDefault("Status", "Active");

var saltBytes = RandomNumberGenerator.GetBytes(16);
var hashBytes = KeyDerivation.Pbkdf2(
    password: adminPassword,
    salt: saltBytes,
    prf: KeyDerivationPrf.HMACSHA256,
    iterationCount: 100000,
    numBytesRequested: 32);

var passwordHash = $"{Convert.ToBase64String(saltBytes)}:{Convert.ToBase64String(hashBytes)}";

Console.WriteLine("\n" + new string('=', 60));
Console.WriteLine("FIRESTORE ADMIN DOCUMENT");
Console.WriteLine(new string('=', 60) + "\n");

Console.WriteLine("Collection: admins");
Console.WriteLine("Document ID: auto-generated by the app if AdminID is 0\n");

Console.WriteLine($"  FullName (string):        {adminName}");
Console.WriteLine($"  Email (string):           {adminEmail}");
Console.WriteLine($"  PasswordHash (string):    {passwordHash}");
Console.WriteLine("  Role (string):            Admin");
Console.WriteLine($"  OfficeLocation (string):  {officeLocation}");
Console.WriteLine($"  Status (string):          {status}");

Console.WriteLine("\n" + new string('=', 60));
Console.WriteLine("BOOTSTRAP CONFIG");
Console.WriteLine(new string('=', 60) + "\n");

Console.WriteLine("Use these environment variables before starting the app:");
Console.WriteLine($"$env:BootstrapAdmin__Enabled=\"true\"");
Console.WriteLine($"$env:BootstrapAdmin__Email=\"{adminEmail}\"");
Console.WriteLine($"$env:BootstrapAdmin__Password=\"{adminPassword}\"");
Console.WriteLine($"$env:BootstrapAdmin__FullName=\"{adminName}\"");
Console.WriteLine($"$env:BootstrapAdmin__OfficeLocation=\"{officeLocation}\"");
Console.WriteLine($"$env:BootstrapAdmin__Status=\"{status}\"");
Console.WriteLine("$env:BootstrapAdmin__OverwriteExisting=\"false\"");

Console.WriteLine("\n" + new string('=', 60));
Console.WriteLine("MANUAL FIRESTORE JSON");
Console.WriteLine(new string('=', 60) + "\n");

var json = $@"{{
  ""AdminID"": 0,
  ""FullName"": ""{adminName}"",
  ""Email"": ""{adminEmail}"",
  ""PasswordHash"": ""{passwordHash}"",
  ""Role"": ""Admin"",
  ""OfficeLocation"": ""{officeLocation}"",
  ""Status"": ""{status}""
}}";

Console.WriteLine(json);

static string ReadRequired(string label)
{
    while (true)
    {
        Console.Write($"{label}: ");
        var value = Console.ReadLine()?.Trim();
        if (!string.IsNullOrWhiteSpace(value))
        {
            return value;
        }

        Console.WriteLine($"{label} is required.");
    }
}

static string ReadWithDefault(string label, string defaultValue)
{
    Console.Write($"{label} [{defaultValue}]: ");
    var value = Console.ReadLine()?.Trim();
    return string.IsNullOrWhiteSpace(value) ? defaultValue : value;
}
